services:
  - type: web
    name: home-service-grbs
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn grbs_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "home-service-grbs.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: home-service-grbs-db
          property: connectionString

databases:
  - name: home-service-grbs-db
    plan: free
