services:
  - type: web
    name: home-service-grbs
    runtime: python
    buildCommand: "cd backend && ./build.sh"
    startCommand: "cd backend && gunicorn grbs_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: home-service-grbs-db
          property: connectionString

databases:
  - name: home-service-grbs-db
    plan: free
